/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:41:22 GMT 2024
 */

package hr.algebra.utils.CustomExceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.utils.CustomExceptions.CustomForbiddenException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CustomForbiddenException_ESTest extends CustomForbiddenException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomForbiddenException customForbiddenException0 = new CustomForbiddenException();
      CustomForbiddenException customForbiddenException1 = new CustomForbiddenException("", customForbiddenException0);
      assertFalse(customForbiddenException1.equals((Object)customForbiddenException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CustomForbiddenException customForbiddenException0 = new CustomForbiddenException();
      CustomForbiddenException customForbiddenException1 = new CustomForbiddenException(customForbiddenException0);
      assertFalse(customForbiddenException1.equals((Object)customForbiddenException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CustomForbiddenException customForbiddenException0 = new CustomForbiddenException("uuW~nUalv#");
  }
}
